name: Build and deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.4'

    - name: Install dependence
      run: go get ./... && go install github.com/gopherjs/gopherjs@v1.18.0-beta1

    - name: Build
      run: make release

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          artifacts/*

    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      if: startsWith(github.ref, 'refs/tags/')
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=public --prod
